### ISSUE TITLE
3. Expenses Type Manager

### ISSUE THREAD

**Issue by kristiyanpetkov** [clouway-incubator/scrum#10]
**Feature**
![screenshot from 2016-06-30 16-23-55](https://cloud.githubusercontent.com/assets/12229738/16489638/1774a51e-3edf-11e6-81a0-707db04b30d1.png)

 **Notes:** Expenses Manager is a separate page, accesed with a button from the main expenses app, where it is possible only to add, edit, or delete different types of expenses;

**Acceptance criteria:**
- All employees can add expenses types
- Only employee logged in as an administrator can delete and edit expenses types
- Employees shouldn't be allowed to add twice one and the same expense type.

**Test scenarios:**
**Given** employee, who is already authenticated,
**When** click on the add button **AND** add a new type of expense
**Then** the new type of expense will be added in the insert expenses page dropdown menu.

**Given** employee, who is already authenticated,
**When** try to add an expense type, which already exist,
**Then** he will be redirected to the same page with a relevant error message.

**Given** employee, who is not authenticated,
**When** attempt to access the expenses manager page,
**Then** he will be redirected to the login page with a relevant error message.

**Given** employee, who is authenticated as an administrator,
**When** attempt to  delete expenses type,
**Then** the expenses type disappear from the insert expenses page dropdown menu.

**Given** employee, who is authenticated as an administrator,
**When** attempt to  edit expenses type,
**Then** the expenses type is changed in the insert expenses page dropdown menu.

**Comment by panayotkulchev** [comment]
LGTM
