### ISSUE TITLE
2. Add An Expense

### ISSUE THREAD

**Issue by kristiyanpetkov** [clouway-incubator/scrum#11]
**Feature**
![screenshot from 2016-07-01 17-10-56](https://cloud.githubusercontent.com/assets/12229738/16523987/caeb26f2-3fae-11e6-9239-097f7263151b.png)

**Notes:**
 The app should have "ADD EXPENSE" button, from where a modal window appears.
The app must identificate the user who made the expense and should generate invoice number, which is incremented on each request.

 Modal window should contain 
a)Fields:
- date (when the expense has been made)
- type of the expense
- quantity 
- amount

b) Button:
- "SAVE EXPENSE"

**Acceptance criteria:**
The employee should be authenticated in attempt to make a request with an expense in the table.
All fields in the modal window should be filled.
Validator should check if all fields are valid. If not , a relevant message appears on the bottom of the modal window.
If all fields are validated and "SAVE EXPENSE" button is clicked, the request is send and saved in the expenses history table.

**Test scenarios:**
**GIVEN** employee, who is already authenticated from the system,
**WHEN** fill all fields correct and click on the "ADD EXPENSE" button
**THEN** a request should be send and the data should be saved in the expenses history table.

**GIVEN** employee, who is already authenticated from the system,
**WHEN** forget to fill a field , or all of the fields and click on "ADD EXPENSE" button
**THEN** an error message should appear on the bottom of the modal window.

**GIVEN** employee, who is already authenticated from the system,
**WHEN** fill all fields, but some of them are not validated and click on "ADD EXPENSE" button
**THEN** an error message should appear on the bottom of the modal window.

**Comment by panayotkulchev** [comment]
All is good. Did not see to mention if expence is registered the list with expences is updated. Do not change just want to metnion

**Comment by panayotkulchev** [comment]
LGTM
