### ISSUE TITLE
1. Expenses

### ISSUE THREAD

**Issue by kristiyanpetkov** [clouway-incubator/scrum#12]
**Feature**
![screenshot from 2016-07-01 16-56-43](https://cloud.githubusercontent.com/assets/12229738/16525070/5553e50a-3fb3-11e6-8784-79e94ff44914.png)

**Notes:**
All requested expenses should be displayed in a table.
The table should contain columns:
- date (when the expense has been made)
- invoice number of the expense
- name of the employee who made the expense
- type of the expense
- quantity
- amount 

The table should have drop down menus for
- date "from"
- date "to"
- all employees or a certain employee

**Acceptance criteria:**
The user should be authorized as an administrator in attempt to make queries from the table.
If user is not authorized, an error message appears saying " You are not authorized to do that! ".
In attempt to make a query, an option should be chosen in each dropdown menu.
Pagination should exist, If the query is too large.

**Test Scenarios:**
**GIVEN** user, who is authorized as an administrator
**WHEN** select certain period and certain employee
**THEN** all expenses made by this employee in this period should be displayed in the table.

**GIVEN** user, who is NOT authorized as an administrator
**WHEN** select certain period and certain employee
**THEN** an error message appears.

**GIVEN** user, who is authorized as an administrator
**WHEN** forget to select period or an employee, or both
**THEN** an error message appears.

**GIVEN** user, who is authorized as an administrator
**WHEN** select certain period and all employees.
**THEN** all expenses made by all employees in this period should be displayed in the table.

**Comment by kristiyanpetkov** [comment]
@mlesikov  , @panayotkulchev  , I am ready with my user stories. Please, when u have time make me a review.

**Comment by panayotkulchev** [comment]
Suggestion. If you have period as filter bu default current date can be selected so in third scenario no error will happen. Do not change. LGTM
