### ISSUE TITLE
whole expenses history

### ISSUE THREAD

**Issue by KrasimirRaikov** [clouway-incubator/scrum#14]
As a manager, I want to input expenses , so that I can get report on those expenses

Importance: 150

Estimate: 4

Given that the manager is authenticated
When he input correct expenses and requests expenses report,
then he should be displayed the expenses report.

Given that the manager is authenticated
When he input incorrect expenses,
then he should be displayed message that the entered data is incorrect.

**Comment by panayotkulchev** [comment]
`When he input...` instead of `When they`

**Comment by KrasimirRaikov** [comment]
I meant it as a gender neutral, but I have made it to ```he```

**Comment by panayotkulchev** [comment]
LGTM!
