### ISSUE TITLE
employee expenses history

### ISSUE THREAD

**Issue by KrasimirRaikov** [clouway-incubator/scrum#17]
As a manager, I want to get a report of the expenses of any chosen employee, so that I may get an estimate of the expenses he/she is making.

Importance: 130

Estimate: 5

Given that the manager is authenticated.
When he make a correct request for employees expenses report,
then he should get that report

**Comment by panayotkulchev** [comment]
Could you please choose more descriptive naming Register what... cars, expenses, employees. This is for all user stories.

**Comment by KrasimirRaikov** [comment]
Renamed ```Register``` to ```Register employee```

**Comment by mgenov** [comment]
What is the Value in the employee registration?

**Comment by mgenov** [comment]
Valuable from Invest states: 

The focus here is to bring actual project-related value to the stakeholder. Coming up with technical PBIs that are really fun to code but bring no value to the stakeholders violates one of the Agile Principles, which is to continuously deliver valuable software.[3]

Source: https://en.wikipedia.org/wiki/INVEST_(mnemonic)

**Comment by panayotkulchev** [comment]
May be `login and register` can be combined in `Employee authentication` or `User authentication` Then the value will be that the system will restrict the people that can add experiences to the it

**Comment by KrasimirRaikov** [comment]
well, the value is to be able to keep data of the employee for further usage.

**Comment by mgenov** [comment]
I have 1 Millions records but I cannot retrieve them. Why do I need these records at all ?

**Comment by KrasimirRaikov** [comment]
Because this way we know we have 1 Million employees, and how to contact them if needed, and so on. And when using the system we use this information to authorize them.

**Comment by KrasimirRaikov** [comment]
I could merge ```login``` and ```registration``` but I think that we can use the data gathered from the ```registration``` for more then just authorization.

**Comment by mgenov** [comment]
It doesn't matter how many employees you have if you cannot contact and one of them.

Valuable is finding contact phone of employee by using part of employee name. 

You can make this with just an InMemory implementation without a persistence and users will be able to find out contacts. Yeah, a short list, but they will be able to.

**Comment by mgenov** [comment]
Authorization = what user is permitted to do (User can issue invoices. User can enter expenses). 
Authentication = who are you ? (I'm John) 

Actually Authentication is not valuable. User information is valuable when expenses report is displayed (who made that expense, who entered that expense). 

What If I pay on my employees on entered expenses ? 

1000 expenses = 100 $ 
4000 expenses = 400 $ 

So I would like to print salary report per employee 

Employee X, 1000 entered records = 100$ 
Employee Y, 4000 expenses = 400 $ 
Employee Z, 1000 expenses = 100 $ 

Total Cost for employees: 600 $ 

This is valuable for humans !

**Comment by mgenov** [comment]
Keep in mind that if authentication is not working, you will not be able to print correct reports.

**Comment by KrasimirRaikov** [comment]
Does that mean that I have to bring the ```Registration``` and ```Login``` together for authentication, and if so, wouldn't I be making an epic?

**Comment by mgenov** [comment]
I think that I said something opposite. 

If you think that what I said is an Epic, then you can split it to following ones: 

1. Deliver system which allows only single user to report expenses 
2. Deliver system which allows a static list of users to report expenses  (only login with in-memory implementation)
3. Deliver system which allows a dynamic list of users to report expenses (yeah, registration, but it's 3'th on the list)

**Comment by KrasimirRaikov** [comment]
I have meant my ```Employee login``` as your 2nd point , and my ```Register employee``` as your 3th point.

**Comment by KrasimirRaikov** [comment]
Can you specify, what is wrong with my issue?

**Comment by mgenov** [comment]
I already did.

**Comment by KrasimirRaikov** [comment]
Is that better ```As an owner, I want to register an employee, so that they can be recognized when making expenses reports```

**Comment by mgenov** [comment]
What steps you will execute to deliver this feature?

**Comment by KrasimirRaikov** [comment]
well with it written like that, i will have to have the reporting of the expenses ready for this feature, which makes it dependent from it, and is the reason why I avoided writing it like that.

**Comment by mgenov** [comment]
Actually the registration is not making recognition. The recognition is made by the authentication which I already pointed out (who are you? I'm John !). If I follow **Your** Story I would write something like: 

Step 1: User X logs in with it's email and password 
Step 2: User X goes to expenses entry page 
Step 3. User X enters a new expense and registers it into the system and should be available in the expenses report page

To make this story I have to deliver 3 things. 
1. Login Form which to allow some authentication with hardcoded data (email and pass of single user maybe) 
2. Expenses Entry Page (name of expense and amount maybe) 
3. Report Page (to show summary amount of all entered expenses) 

**What Owner of the product gains of this?**
I could record my daily expenses and I could get total report of my expenses after end of the month. 

**What Owner of the product gains of doing just 'Employee Registration'**
I could record my employees. 

If I have to choose between these 2 options I will take the first one for sure !

**Comment by KrasimirRaikov** [comment]
Well put like that there is no value in the registration and the Login issues, should i remove them?

**Comment by mgenov** [comment]
The only think that I care is my team mates to know how to split features. 

@panayotkulchev it's up to you how to proceed.

**Comment by panayotkulchev** [comment]
PBI should cover `As owner I want to record my daily expenses and get expenses report for certain period`. This is like happy path. Then you have the value to view the report. It totally covers `INVEST`.
Later you can have the need `Employees to enter their expenses` witch is other PBI. The second one will  make you create the registration.

This way the owner can view the reports for expenses per employees or per periods. And will have the registration done to achieve the goals without create different PBIs for `registration`.

@mgenov agree?

**Comment by mgenov** [comment]
Yes, looks like a better direction that it was.

**Comment by KrasimirRaikov** [comment]
well, I think I already have the employees input expenses in #13, the question I think is how to split the functionality so that I don't make everything in one story. Isn't it?

**Comment by mgenov** [comment]
I'm not sure that you understand what I was trying to tell you with my comments as You pointed out the similar issue with another story.

For me: "Register Employee" is similar to "Employee Input Expenses"

The value is not in storing some records in the database, the value is in what you are doing with these records.

Your app collects expenses  to be able to report how much money company spends for a period of time, i.e the value is how much money company spends for some period of time.

**Comment by KrasimirRaikov** [comment]
yes, I'll fix that in input expenses, I'll make it "As an employee, I want to be able to input an expense sorted in certain type, so that it can be used for the expenses reporting."

**Comment by KrasimirRaikov** [comment]
but how I split it so that I don't have to make the registration and the login and the input of the expenses in one story? Because I think it is valuable for the customer to have restricted access to this financial app.

**Comment by mgenov** [comment]
I partially completed your task with the following statement:

> To make this story I have to deliver 3 things. 
1. Login Form which to allow some authentication with hardcoded data (email and pass of single user maybe) 
2. Expenses Entry Page (name of expense and amount maybe) 
3. Report Page (to show summary amount of all entered expenses) 

As this is the first feature, which is a base for the remaining ones.  As you can see, only single user could report expenses now and If I want to add multi user support I have to allow multiple users to authenticate, so I need to know which one is John and which one is Peter. And here comes the next feature. 
 * collect expenses then get report of them by a single user (happy path, no authentication, points 1, 2 and 3) 
 * multi user expenses reporting with static list of users
 * make static user list dynamic
 * filtering expenses on monthly base (this will force me to add date field in the expenses report)

**Comment by mgenov** [comment]
https://github.com/clouway-incubator/scrum/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Krasimir%27s+Backlog%22

**Comment by KrasimirRaikov** [comment]
Do you mean this?
```
1.As a manager I want to input expenses and get a report on them.
2.As a manager I want to get a report of the expenses of any chosen employee.
3.As a manager I want to get a report of my firms expenses as a whole.
4.As a manager I want to get a report of my firms expenses for a given month.
```

**Comment by mgenov** [comment]
1 looks same as 3

Overall it looks much better. 

I'm not going to review this task anymore.

**Comment by panayotkulchev** [comment]
Could you describe me how you imagine the second scenario. What do you mean manager to make incorrect request

**Comment by KrasimirRaikov** [comment]
Well, I guess it is not a real scenario, since I would probably choose the employee from a list, being unable to choose the wrong one.

**Comment by KrasimirRaikov** [comment]
I have removed that scenario

**Comment by panayotkulchev** [comment]
`When he ...` instead of `When they ...`

**Comment by KrasimirRaikov** [comment]
made it to ```he```

**Comment by panayotkulchev** [comment]
LGTM!
