### ISSUE TITLE
Expenses report of employee

### ISSUE THREAD

**Issue by Stanislava88** [clouway-incubator/scrum#18]
ID  | NAME | IMP | EST | USER STORY
-----| ---------| ------| ------ |--------------------|
US1|Expenses report of employee| 160 | 6 | As a firm owner i want my employee to be able to insert his expenses so i can get report for him.

``` Scenario:  Employee add expenses ```
Given  that the employee is authenticated
When insert expense correctly
Then this report should be available in the report page .

Given  that the employee is authenticated
When leave empty fields when filling expenses
Then error message should be displayed.

Given  that the employee is authenticated
When insert too big amount for expenses
Then error message should be displayed.

Given  that the employee is authenticated
When insert negative amount for expenses
Then error message should be displayed.

**Comment by stefan-dimitrov** [comment]
LGTM.

**Comment by panayotkulchev** [comment]
LGTM
