### ISSUE TITLE
Expenses report of all employees

### ISSUE THREAD

**Issue by Stanislava88** [clouway-incubator/scrum#19]
ID  | NAME | IMP | EST | USER STORY
-----| ---------| ------| ------ |--------------------|
US2|Expenses report of all employees | 150 | 6 | Аs a firm owner i want to be able to preview the cost statement of all employees so that I can keep statistics on their expenses 

``` Scenario: Report for all employees ```
Given that the firm owner is authenticated 
When he asks to see report for the employees
Then should be available that report.

**Comment by stefan-dimitrov** [comment]
Adding of new employees is a different user story.

**Comment by Stanislava88** [comment]
removed unnecessary scenario.

**Comment by stefan-dimitrov** [comment]
LGTM.

**Comment by panayotkulchev** [comment]
LGTM
