### ISSUE TITLE
Firm expenses report for certain period

### ISSUE THREAD

**Issue by Stanislava88** [clouway-incubator/scrum#20]
ID  | NAME | IMP | EST | USER STORY
-----| ---------| ------| ------ |--------------------|
US5| Firm Expenses Report for certain period | 100| 3 | Аs a firm owner i want to be able to check the all the costs for certain period of time of my firm so that I can keep statistics the expenses of the company 

``` Scenario: Report for all expenses ``` 
Given that the firm owner is authenticated 
When he asks to see report for the entire firm
And the entered period is valid
Then should be returned  that report.

Given that the firm owner is authenticated 
When he asks to see report for the entire firm
And the entered period is invalid
Then an error message should be displayed.

**Comment by stefan-dimitrov** [comment]
LGTM.

**Comment by panayotkulchev** [comment]
LGTM
