### ISSUE TITLE
Edit Expenses Type

### ISSUE THREAD

**Issue by Stanislava88** [clouway-incubator/scrum#21]
ID  | NAME | IMP | EST | USER STORY
-----| ---------| ------| ------ |--------------------|
US6|Edit Expenses Type  | 60 | 2 | As a firm owner i want to be able to add and delete different expenses type so i can add new expenses and delete unnecessary

``` Scenario: Added expenses type ```
Given that the firm owner is authorized 
When he insert  new expenses type
And this type doesn't exists
Then it should be stored.

Given that the firm owner is authorized 
When he insert  new expenses type
And this type exists
Then error message should be displayed.

``` Scenario: Delete expenses type ```
Given that the firm owner is authorized 
When he requests  the deletion of expenses type
And this type exists
Then it should be removed.

**Comment by stefan-dimitrov** [comment]
This should be with lower priority than the other user stories. 
The expense types can be hard-coded in-memory in the beginning. When the need to edit them arises, then this user story can be implemented.

**Comment by Stanislava88** [comment]
The priority changed to 60

**Comment by stefan-dimitrov** [comment]
Looks better now :+1:

**Comment by stefan-dimitrov** [comment]
LGTM.

**Comment by panayotkulchev** [comment]
LGTM
