### ISSUE TITLE
Register Employees

### ISSUE THREAD

**Issue by Stanislava88** [clouway-incubator/scrum#22]
ID  | NAME | IMP | EST | USER STORY
-----| ---------| ------| ------ |--------------------|
US6 | Register Employees | 80 | 3 | Аs a firm owner i want to be able to save insformation for employees, so that they can login to the system. 

``` Scenario: Register employee ```
Given that the firm owner is logged in  
When he register new employee
And input fields data is valid 
Then employee should be stored.

Given that the firm owner is logged in 
When he register new employee
And input fields are incorrect 
Then error message should be displayed.

**Comment by panayotkulchev** [comment]
Could you please choose more descriptive naming `Register` what... cars, expenses, employees. This is for all user stories.

**Comment by panayotkulchev** [comment]
If you mean that owner is logged then should say `Given that the firm owner is authenticated` . Authorization means he has the rights to register employees.
