### ISSUE TITLE
Employees expenses report by type

### ISSUE THREAD

**Issue by Stanislava88** [clouway-incubator/scrum#23]
ID  | NAME | IMP | EST | USER STORY
-----| ---------| ------| ------ |--------------------|
US3 |Employees expenses report by type| 120| 4 | Аs an firm owner  i want to be able to check the all the costs filter by type of my employees so that I can keep statistics the expenses of the employees

``` Scenario: Expenses report by type```
Given that the firm owner is authenticated 
When he asks to see report by type
And the entered type data are valid
Then should be returned that report.

Given that the firm owner is authenticated 
When he asks to see report by type
And the entered data are invalid
Then error message for incorrect data should be displayed.

**Comment by stefan-dimitrov** [comment]
I see that you have a report for period also in the firm expenses story. When is the period filter going to be implemented?

In the user story description it is stated that the report will be for employee expenses. It sounds like it is only for employee expenses, but the name of the story does not suggest such a restriction. One of those two needs to be clarified.

**Comment by Stanislava88** [comment]
renamed user story to ```Employees expenses report for certain period and type```

**Comment by Stanislava88** [comment]
deleted duplicate filtration by period.

**Comment by stefan-dimitrov** [comment]
LGTM.

**Comment by panayotkulchev** [comment]
LGTM
