### ISSUE TITLE
period expenses history

### ISSUE THREAD

**Issue by KrasimirRaikov** [clouway-incubator/scrum#24]
As a manager, I want to be able to get report for a given period for (an employee)/(the firm), so that I can have some idea what expenses is the firm/employee made for that period.

Importance: 140

Estimate: 3

Given that the manager is authenticated.
When they request a report for the expenses for a given correct period
then they should be displayed the firms expenses report.

Given that the manager is authenticated.
When they request a report for the expenses for a given correct period and maybe employee id,
then they should be displayed the expenses report for that employee on that date.

Given that the manager is authenticated.
When they request a report for the expenses for a given incorrect period,
then they should be displayed message that the specified period is incorrect.

**Comment by panayotkulchev** [comment]
I think the last scenario should be not reachable. I mean that the workflow should be that the client is not able to make mistakes so can not enter inccorect employee id.

**Comment by KrasimirRaikov** [comment]
removed that scenario

**Comment by panayotkulchev** [comment]
LGTM!
