### ISSUE TITLE
expenses history by type

### ISSUE THREAD

**Issue by KrasimirRaikov** [clouway-incubator/scrum#25]
As a manager, I want to request the expenses for a given type, so that I know the expenses in this type

Importance: 110
Estimate: 2

Given that the manager is authenticated
When he requests expenses report for a given type,
then he should be given that report.

Given that the manager is authenticated
When the manager want to get report for new type of expenses, he should be able to add it in nomenclature, then the manager is displayed a message upon success.

Given that the manager is authenticated
When the manager want to remove unused type from the nomenclature, then the manager is displayed a message upon success.

**Comment by panayotkulchev** [comment]
In this issue will be the place where you will add `expencesType` probably as nomenclature. I do not understand it from anywere. Be more descriptive.

**Comment by panayotkulchev** [comment]
The way it is written I understand that the PBI is for filtering the reported expences by type. Is this correct or it is page where you can add different types like: `FUEL`, `COURSES`, `FOOD`... ?

**Comment by KrasimirRaikov** [comment]
it is that I filter the report by type, which makes it necessary to have them entered in categories.

**Comment by panayotkulchev** [comment]
yes. I ment to describe it better but now is Ok

**Comment by panayotkulchev** [comment]
In othe issue you have 
```
Importance: 140
Estimate: 3
```
And here you do not have

**Comment by KrasimirRaikov** [comment]
I have overlooked it, sorry. I have given it Importance 140, and estimate 2

**Comment by panayotkulchev** [comment]
LGTM
