### ISSUE TITLE
Edit employees

### ISSUE THREAD

**Issue by Stanislava88** [clouway-incubator/scrum#27]
ID  | NAME | IMP | EST | USER STORY
-----| ---------| ------| ------ |--------------------|
US4| Edit employees | 80 | 3 |  As a firm owner i want to edit employees so i can add new employees and make report for them and remove  employees
 
```Scenario: Add new employees ```

Given that a firm owner is authenticated
When he add new employee
And all fields are correct
And this employee is not exists
Then this employee should be saved 
And report for him can be maked

Given that a firm owner is authenticated
When he add new employee
And any fields are incorrect
Then should be displayed error message

Given that a firm owner is authenticated
When he add new employee
And this employee exists
Then should be displayed error message

```Scenario: Remove employees ```
Given that the firm owner is authorized 
When he requests the deletion of employee
And this employee exists
Then he should be removed.

Given that the firm owner is authorized 
When he requests the deletion of employee
And this employee not exists
Then error message should be displayed.

**Comment by stefan-dimitrov** [comment]
The description of the story sounds like the employees are similar to the reports - stored so they can be viewed. Isn't the goal of saving new employees different?

**Comment by Stanislava88** [comment]
renamed to ```Expenses report for new employees```

**Comment by stefan-dimitrov** [comment]
That way the user story name is not accurate to the description. The first name was on the right track. Something like `Register new employees` or even `Edit employees`, because if you are adding employees you probably would want to be able to remove some.

**Comment by Stanislava88** [comment]
renamed to ```Edit employees ``` 
added scenario: ```Remove employees```

**Comment by stefan-dimitrov** [comment]
LGTM.

**Comment by panayotkulchev** [comment]
LGTM
