### ISSUE TITLE
Filter for cost reporting by date

### ISSUE THREAD

**Issue by p-nedelchev** [clouway-incubator/scrum#32]
Application should allow filtering the cost report by date

Test scenarios:
- method for cost report is invoked with date parameter. It should return the list of cost for that date. 
- method for cost report is invoked with 2 date parameters - first begin date and second end date. It should return a list with all cost registered in the given interval

Note: For test scenarios costs must be prepared for different days for every test.

Asignee: @tsony-tsonev

**Comment by tsony-tsonev** [comment]
In the test scenarios you should note that costs must be prepared for different days for every test.

**Comment by p-nedelchev** [comment]
I added as a note below test scenarios
