### ISSUE TITLE
Filter cost reports by months

### ISSUE THREAD

**Issue by p-nedelchev** [clouway-incubator/scrum#33]
Application should allow filtering for cost reports by months. 

Test scenarios: 
- Cost reporting method is invoked with parameter for month. It should return a list with all costs for that month.
- Cost reporting method is invoked with 2 months parameters - first for begin month and second for end month. It should return a list with all cost  registered in the interval.

Note: For test scenarios costs must be prepared for different month for every test.
 
Asignee: @tsony-tsonev

**Comment by tsony-tsonev** [comment]
In the test scenarios you should note that costs must be prepared for different months for every test.

**Comment by p-nedelchev** [comment]
I added it as a note below test scenarios.
