### ISSUE TITLE
Create page to add and visualize expenses

### ISSUE THREAD

**Issue by slavidichkov** [clouway-incubator/scrum#5]
We should have page where we should able to add new expenses, also we should be able to visualise them.

- should have a button to add new expense (fig. 1)

- modal dialog should be shown after clicking on the add button (fig. 2)

- when click submit button of modal check if data is not valid error message appear (fig. 3)

- if data is valid storage new expense in repository (fig. 4)

- table must show last added expenses  (fig. 5)

**note**
`
If expenses nomenclature type page is ready the  expense type field should be dropdown with the values of the nomenclature 
`

![7](https://cloud.githubusercontent.com/assets/12229758/15183378/82d36a42-1799-11e6-86cb-cd409cf97426.png)
fig. 1

![8](https://cloud.githubusercontent.com/assets/12229758/15183383/8a95a740-1799-11e6-963c-7c9a024afe99.png)
fig. 2

![3](https://cloud.githubusercontent.com/assets/12229758/15183948/f9cae056-179b-11e6-856a-647d08bdee66.png)

fig. 3

![4](https://cloud.githubusercontent.com/assets/12229758/15183146/85ed5e82-1798-11e6-85be-2423c1c50c9e.png)
fig. 4

![10](https://cloud.githubusercontent.com/assets/12229758/15183394/961ed852-1799-11e6-8e41-f2b77c2c0a27.png)
fig. 5

Test scenarios:
- when page is loaded after clicking on the button a modal should be opened
- when page is loaded after clicking multiple times on the button a single modal should be opened
- when click submit button must check if there is such an employee and if are valid quantity, invoice number, date, expense value. If data is valid storage new expense in repository after expense is storage modal should be closed
-  when the save of expense is not successful , an error message appear and  then the modal should stay opened.

**Comment by tsony-tsonev** [comment]
Missing scenario, for when the save of expense is not successful (then the modal should stay opened and a pop-up message should be shown with some error)
