### ISSUE TITLE
Create expense types nomenclature

### ISSUE THREAD

**Issue by slavidichkov** [clouway-incubator/scrum#7]
There should be a page which should manage expense types nomenclature, page must be accessed only by users with special rights

Should have:
- add type
- remove type

![15](https://cloud.githubusercontent.com/assets/12229758/15391429/d06905d8-1dc9-11e6-9821-ae663b37d8a5.png)

**note** 
`
If expenses page is ready it's expense type field shoud be changed to dropdown with the values of the nomenclature 
`

Test scenarios:

- when user without special rights try to open page with nomenclatures he must be redirected to home page
-  when the user is authorized nomenclatures page will be open
-  when user try to add same type more than once an error message appear
-  when user try to delete already deleted type an error message  appear

**Comment by tsony-tsonev** [comment]
You should have more scenarios. Now you have scenario only for unauthorized acces. You should also have scenarios for when the user is authorized. When he adds same type more than once, or when he tries to delete not existing type.
