### ISSUE TITLE
5. Registration 

### ISSUE THREAD

**Issue by kristiyanpetkov** [clouway-incubator/scrum#8]
**Feature**
![screenshot from 2016-06-30 10-06-56](https://cloud.githubusercontent.com/assets/12229738/16479641/66b017ec-3eaa-11e6-8bbe-17d7687e6bcc.png)

**Acceptance criteria:**

- An existing user cannot re-register and will receive an error message on attempt.
- All fields must be entered to successfully register
- All fields must be in a valid format, according to the validation requirements.
- On successful registration, a new account is assigned and a registration email is sent.

**Test scenarios:**
**Given** user does not exist in the system, 
**When** the registration form is correctly filled and the registrant clicks on "SIGN UP" button,
**Then** a new account is created.

**Given** user already exist in the system,
**When**  the registration form is correctly filled and the registrant clicks on "SIGN UP" button,
**Then** an error message appear on the display.

**Given** user already exist in the system.
**When**  the registration form is empty and the registrant clicks on "SIGN UP" button,
**Then** an error message appear on the display.

**Given** user already exist in the system.
**When** the registration form is filled with invalid data and the registrant clicks on "SIGN UP" button,
**Then** an error message appear on the display.

**Comment by panayotkulchev** [comment]
When you say user is already registered what does it mean. User with same nickname or with same email... I mean will be good to be mentioned. All is good. LGTM
