### ISSUE TITLE
4. Login

### ISSUE THREAD

**Issue by kristiyanpetkov** [clouway-incubator/scrum#9]
**Feature**
![screenshot from 2016-06-30 15-34-51](https://cloud.githubusercontent.com/assets/12229738/16488218/32cb5c38-3ed8-11e6-8caa-f254dd30ca26.png)

**Acceptance criteria:**
- All fields in the form must be filled.
- User, who is already logged in, cannot access the login page.
- An error message appear when user login data is invalid or wrong.

**Test scenarios:**
**Given** user who is already registered in the system,
**When** the login form is filled correctly and login button is clicked,
**Then** he is redirected to the expenses app.

**Given** user who hasn't been registered in the system,
**When** try to log in with unauthenticated data,
**Then** he is redirected to the login page with the relevant error message.

**Given** user who is already registered in the system,
**When** try to log in with wrong password,
**Then** he is redirected to the login page with the relevant error message.

**Given** user who is registered or not registered,
**When** try to log in with empty field/s,
**Then** he is redirected to the login page with the relevant error message.

**Given** user who is already logged in the system,
**When** try to access login page,
**Then** he is redirected to the expenses app.

**Comment by panayotkulchev** [comment]
LGTM
